# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Adeeb Ibne Amjad's Portfolio Site
email: adeeb.amjad@mail.mcgill.ca
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my site! I am a third year software engineering student at McGill University. 
  I was VP Events for the Bangladeshi Students Association (BSA) McGill from 2015-16. Currently
  I am working with the controls team of Aero McGill to develop a drop strategy for the upcoming 
  SAE Aero Design West competition in Fort Worth, Texas, USA.
baseurl: "" # the subpath of your site, e.g. /blog
# the base hostname & protocol for your site
twitter_username: shadaraamarusernamebujhena
github_username:  adeeb27
# Build settings
markdown: kramdown
